spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hello
          uri: lb://eureka-client
          predicates:
            - Method=GET
            - Path=/main/hello

        - id: testHello
          uri: lb://eureka-client-1
          predicates:
            - Method=GET
            - Path=/test/hello

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
